#!/bin/bash

docker run \
	--restart always \
	--publish=7474:7474 \
	--publish=7687:7687 \
	-e NEO4J_apoc_export_file_enabled=true \
	-e NEO4J_apoc_import_file_enabled=true \
	-e N0EO4J_apoc_import_file_use__neo4j__config=true \
	-e NEO4J_PLUGINS=\[\"apoc\"\] \
	neo4j:5.13.0-community-ubi8

